// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SeyirAkademi_v1._1.Models;

namespace SeyirAkademi_v1._1.Migrations
{
    [DbContext(typeof(DocContext))]
    [Migration("20230101031812_00")]
    partial class _00
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SeyirAkademi_v1._1.Models.Doc", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DocCategoryID")
                        .HasColumnType("int");

                    b.Property<int>("DocTypeId")
                        .HasColumnType("int");

                    b.Property<string>("FileURL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageURL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ShortDescription")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("DocCategoryID");

                    b.ToTable("Docs");
                });

            modelBuilder.Entity("SeyirAkademi_v1._1.Models.DocCategory", b =>
                {
                    b.Property<int>("DocCategoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DocCategoryName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DocCategoryID");

                    b.ToTable("DocCategories");
                });

            modelBuilder.Entity("SeyirAkademi_v1._1.Models.Doc", b =>
                {
                    b.HasOne("SeyirAkademi_v1._1.Models.DocCategory", "DocCategory")
                        .WithMany("Docs")
                        .HasForeignKey("DocCategoryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DocCategory");
                });

            modelBuilder.Entity("SeyirAkademi_v1._1.Models.DocCategory", b =>
                {
                    b.Navigation("Docs");
                });
#pragma warning restore 612, 618
        }
    }
}
